export function prepareMarkdown(text: string): string {
  if (!text) return "";
  let clean = text;

  // 2. Unescape \$ -> $
  clean = clean.replace(/\\\$/g, "$");

  // Helper to safely format math content by replacing | with \vert 
  // to prevent remark-gfm from misinterpreting them as markdown tables.
  // Also fixes KaTeX parse errors for unbraced macro superscripts (e.g. ^\dagger -> ^{\dagger})
  const safeMath = (math: string) => {
    let m = math.replace(/\|/g, "\\vert ");
    m = m.replace(/(\^|_)\\([a-zA-Z]+)/g, "$1{\\$2}");
    return m;
  };

  // 3. Handle double-escaped \\( \\) and \\[ \\] from JSON
  clean = clean.replace(/\\\\([[(])([\s\S]*?)\\\\([\])])/g, (_, open, content, close) => {
    if (open === "[" && close === "]") return `\n\n$$${safeMath(content).trim()}$$\n\n`;
    if (open === "(" && close === ")") return `$${safeMath(content).trim()}$`;
    return _;
  });

  // 4. Single-escaped \[ ... \] -> $$ ... $$
  clean = clean.replace(/\\\[([\s\S]*?)\\\]/g, (_, p1) => `\n\n$$${safeMath(p1).trim()}$$\n\n`);

  // 5. Single-escaped \( ... \) -> $ ... $
  clean = clean.replace(/\\\(([\s\S]*?)\\\)/g, (_, p1) => `$${safeMath(p1).trim()}$`);

  // 6. Backtick-wrapped LaTeX on its own line -> display math
  clean = clean.replace(/(?:^|\n)\s*`([^`\n]*?\\[a-zA-Z]+[^`\n]*?)`\s*(?:\n|$)/g, (_, p1) => `\n\n$$${safeMath(p1).trim()}$$\n\n`);

  // 7. Inline backtick-wrapped LaTeX -> inline math
  clean = clean.replace(/`([^`\n]*?\\[a-zA-Z]+[^`\n]*?)`/g, (_, p1) => `$${safeMath(p1).trim()}$`);

  // 7.5. Wrap bare \begin{env}...\end{env} blocks that the AI emitted without
  //       surrounding $$ or \[...\] delimiters.  We only target the KaTeX
  //       environments that make sense as standalone display math.
  //       The negative lookbehind prevents double-wrapping when the environment
  //       is already inside $$...$$ written by the AI.
  const mathEnvPattern =
    "align|aligned|equation|gather|gathered|" +
    "array|matrix|pmatrix|bmatrix|vmatrix|Vmatrix|" +
    "cases|multline|split|eqnarray";
  clean = clean.replace(
    new RegExp(
      `(?<!\\$\\$\\s*)(\\\\begin\\{(?:${mathEnvPattern})[*]?\\}[\\s\\S]*?\\\\end\\{(?:${mathEnvPattern})[*]?\\})(?!\\s*\\$\\$)`,
      "g"
    ),
    (match) => `\n\n$$${safeMath(match.trim())}$$\n\n`
  );

  // 8. Safely handle already existing $$ ... $$ and $ ... $ natively generated by AI
  clean = clean.replace(/\$\$([\s\S]*?)\$\$/g, (match, p1) => {
    return `$$${safeMath(p1)}$$`;
  });
  
  // Safely handle already existing $ ... $
  // We apply safeMath to ensure any | inside native inline math is escaped.
  clean = clean.replace(/(^|[^\\])\$([^$\n]+?)\$/g, (match, before, inner) => {
    // We replace | with \vert to prevent table breaks
    return `${before}$${safeMath(inner)}$`;
  });

  // 9. Fix squished table rows which remark-gfm hates
  clean = clean.replace(/\|\s*\|\s*([:-]+)/g, "|\n| $1");
  clean = clean.replace(/\|\s*\|\s*([^\s|])/g, "|\n| $1");

  return clean;
}
